name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to Google Cloud
        run: echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Terraform Init
        run: |
          cd terraform
          export TF_VAR_gcp_credentials=$(cat ../gcp-key.json)
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          export TF_VAR_gcp_credentials=$(cat ../gcp-key.json)
          terraform apply -auto-approve
